store/urls.py
from django.urls import path,include
from .views import IndexView
from . import views


urlpatterns = [
    path('', IndexView, name='index'),
    path('records/', views.records, name='records'),
    path('services/', views.services, name='services'),
    path('goods/checkout/<records_id>/',views.checkout_booking,name='checkout'),
    path('checkout-goods/<int:goods_id>/',views.checkout_goods,name='checkout_goods'),
    path('register/',views.register, name='register'),
    path('client_register/',views.client_register.as_view(), name='client_register'),
    path('staff_register/',views.staff_register.as_view(), name='staff_register'),
    path('client_login/',views.client_login, name='client_login'),
    path('staff_login/',views.staff_login, name='staff_login'),
    path('logout/',views.logout_view, name='logout'),
    path("change_password/", views.change_password, name="change_password"),
    path("admin_login/", views.admin_login, name="admin_login"),
    # path('client_profile/', views.client_profile, name='client_profile'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('profile/', views.profile, name='profile'),
    # path('staff_profile/', views.staff_profile, name='staff_profile'),
    # path('update_staff_profile/',views.update_staff_profile, name='update_staff_profile'),
    path('update_profile/<int:id>',views.update_profile, name='update_profile'),
    # path('accounts/profile/', views.IndexView,name='index'),
    # path('update_client_profile/',views.update_client_profile, name='update_client_profile'),
    path('social-auth/',include('social_django.urls',namespace='social')),
    path('api/store/', views.Storelist.as_view()),
    path('news/', views.blog, name='blog')
    
    

]
handler404 = "store.views.page_not_found_view"

store_centre/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('',include('store.urls')),
    path('delivery/', include('transport.urls')),
    path('units/',include('units.urls')),
    path('analytics/', include('analytics.urls')),
    path('api-token-auth/', obtain_auth_token),
    path('paypal/', include('paypal.standard.ipn.urls')),

  
    
    
    
]
handler404 = "store.views.page_not_found_view"

units/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<storage_type>',views.display_units,name='units'),
    path('',views.dashboard,name='dashboard'),
    path('book/',views.book_unit,name='book'),
   
]

units/models.py
from django.db import models

from store.models import User

class Storage(models.Model):
    type = models.CharField(max_length=100) #type of storage
    charge = models.IntegerField() #cost per unit
    no_units = models.IntegerField(default=0) #total number of units in a storage type
    available_units = models.IntegerField(default=0) # remaining units 

    def __str__(self):
        return self.type

    def add_storage(self):
        self.save()
        
    def remove_storage(self):
        self.delete()
    
    @classmethod    
    def all_storages(self):
        storages = Storage.objects.all()
        return storages
    @classmethod
    def storage_type(self,type):
        storage = Storage.objects.filter(type=type).first()
        return storage
    @classmethod
    def units_available(self,type):
        storage = Storage.objects.filter(type =type).first()
        units = storage.available_units
        return units;

    
    
    
class Goods(models.Model):
    storage_type  = models.ForeignKey(Storage,on_delete=models.CASCADE,related_name='units') #type of storage
    no_of_units = models.IntegerField(null=True)
    arrival_date = models.DateField()
    departure_date = models.DateField()
    description = models.TextField(max_length=500)
    total_cost = models.IntegerField(null=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE,related_name='goods')
    
    def __str__(self):
        return str(self.owner)

    def add_goods(self):
        self.save()

    def remove_goods(self):
        self.delete()
        
    def owner_goods(self,owner):
        goods = Goods.objects.filter(owner=owner).all()
        return goods;

    

units/forms.py
from inspect import Attribute
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from .models import Goods,Storage
from django.forms.widgets import Select, SelectMultiple




class SelectWOA(Select):
    """
    Select With Option Attributes:
        subclass of Django's Select widget that allows attributes in options, 
        like disabled="disabled", title="help text", class="some classes",
              style="background: color;"...

    Pass a dict instead of a string for its label:
        choices = [ ('value_1', 'label_1'),
                    ...
                    ('value_k', {'label': 'label_k', 'foo': 'bar', ...}),
                    ... ]
    The option k will be rendered as:
        <option value="value_k" foo="bar" ...>label_k</option>
    """

    def create_option(self, name, value, label, selected, index, 
                      subindex=None, attrs=None):
        if isinstance(label, dict):
            opt_attrs = label.copy()
            label= opt_attrs.pop('label')
        else: 
            opt_attrs = {}
        option_dict = super(SelectWOA, self).create_option(name, value, 
            label, selected, index, subindex=subindex, attrs=attrs)
        for key,val in opt_attrs.items():
            option_dict['attrs'][key] = val
        return option_dict


class StorageForm(forms.ModelForm):


    class Meta:
        model = Storage
        fields = ('type','charge','no_units','available_units')

class GoodsBookingForm(forms.Form):
    storages = Storage.objects.all()
    choices =[( storage,{'label':storage.type,'charge':storage.charge }) for storage in storages]
    # choicess = [('b', 'blue'),
    #        ('g', {'label': 'green', 'disabled': 'disabled','value':'purple'}),
    #        ('c', {'label': 'cyan', 'title': 'Kind of violet', 'style': 'background: cyan;', }),
    #        ('r', 'red'), ]

    storage_type = forms.ChoiceField(choices=choices, label="storage",widget=SelectWOA)
    description = forms.CharField(widget=forms.TextInput(attrs={'style':"border-radius: 5px;" ,'name':"description", 'id':"description",'class':"form-control" ,'cols':"30", 'rows':"10" }))
    no_of_units =forms.IntegerField(widget=forms.NumberInput(attrs={'type':"number",'min':"1",'name':"no_of_units", 'id':"no_of_units", 'placeholder':"number of units"}))
    arrival_date =forms.DateField(widget=forms.DateInput(attrs={'type':'date','class':"form-control" ,'type':"date" ,'oninput':"total()", 'name':"arrival_date", 'id':"arrival_date"}))
    departure_date = forms.DateField(widget=forms.DateInput(attrs={'type':'date','class':"form-control" ,'type':"date" ,'oninput':"total()", 'name':"departure_date", 'id':"departure_date"}))
    total_cost = forms.IntegerField(widget = forms.NumberInput(attrs ={'class':"form-control", 'type':'number','id':"total_cost"}))
    class Meta:
        
        fields = ('storage_type','no_of_units','description','arrival_date','departure_date','Total_cost')

           

units/views.py
import re
from django.shortcuts import render,redirect,get_object_or_404
from .models import *
from transport.models import *
from .forms import StorageForm,GoodsBookingForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
@login_required(login_url = '/client_login')
def book_unit(request):
    
    if request.method == 'POST':
        form = GoodsBookingForm(request.POST)
        if form.is_valid():
            
            storage_type= form.cleaned_data.get('storage_type')
            arrival_date= form.cleaned_data.get('arrival_date')
            departure_date= form.cleaned_data.get('departure_date')
            description = form.cleaned_data.get('description')
            no_of_units= form.cleaned_data.get('no_of_units') # available units
            total_cost = form.cleaned_data.get('total_cost') 
        
            
            units = Storage.objects.filter(type=storage_type).first() 
            #transport logic
            initial_units = units.available_units
            request.session['initial_units']=initial_units
            if units.available_units >= no_of_units:
                storage =  get_object_or_404(Storage,type=storage_type)
                booked_unit =  Goods(storage_type =storage,no_of_units=no_of_units,arrival_date=arrival_date,departure_date=departure_date,description =description,owner =request.user,total_cost=total_cost)
                booked_unit.add_goods()
                storage = Storage.objects.filter(type=storage_type).first()
                storage.available_units -= no_of_units
                storage.add_storage() 
                #transport logic
                final_units = storage.available_units
                request.session['final_units']=final_units
                messages.success(request,f'Booked successfully')
                return redirect('request_transport')

            else:
                messages.error(request,f'No slots available in {storage_type} try again later')
                return redirect('book')
        else: 
            messages.error(request,f'Something went wrong')
            return redirect('book')

    else:
        form = GoodsBookingForm()
        storage_types = Storage.objects.all()

    context = {
        
        "form": form,
        "storage_types": storage_types
    }
    return render(request,'booking.html',context)

def dashboard(request):
    storages = Storage.objects.filter()
    
    if request.method == 'POST':
        form = StorageForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,f'Booked successfully')
        else:
            messages.error(request,'Something went wrong')
        return redirect('dashboard')
            
    else:
        form = StorageForm()


        args = {
            "storages": storages,
            "form":form
        }
        return render(request,'staff_dashboard.html',args)

def display_units(request,storage_type):

    
    goods = Goods.objects.filter(storage_type=storage_type)

    form = StorageForm()

    context = {
        "goods": goods,
        "storage_type":storage_type,
    }

    return render(request,'units.html',context)

templates/admin_login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Store Centre {% endblock %}
{% block css %}
{% endblock %}
{% block content %}

<div class="overlay"
  style="box-shadow:inset 0 0 0 2000px rgba(23, 34, 23, 0.863);background-image: url(/static/images/hero_1.jpg);color: white;"
  data-aos="fade" id="home-section">


  <div class="container">
    <div class="row align-items-center justify-content-center">
      <div class="col-md-6 mt-lg-5 text-center">
        <br><br>
        <h1>Admin Login</h1>
        <div style="margin-bottom: 10px;">
        </div>
      </div>
    </div>
  </div>
  <br><br>
  <a href="#heading" class="smoothscroll arrow-down"><span class="icon-arrow_downward"></span></a>
</div>


<!-- <div class="container">
<br>
<h1 class="text-center"><u></u></h1><br>
<p><b>Note:</b> Only the admin can login from here. No Client will be allowed to login.</p>
    <form method="POST"> {% csrf_token %}

    <div class="row mt-4">
        <div class="form-group col-md-12">
            <label><i style="font-weight: bold;">Username</i></label>
            <input type="text" class="form-control mt-2" name="username" placeholder="Enter Username" required>
        </div>
    </div>

    <div class="row mt-4">
        <div class="form-group col-md-12">
            <label><i style="font-weight: bold;">Password</i></label>
            <input type="password" class="form-control mt-2" name="password" placeholder="Enter Password" required>
        </div>
    </div>
    <button type="submit" class="btn btn-outline-primary mt-4">Login</button>
</div>
 -->



<div style="margin-top: -90px;" class="limiter">
  <div class="wrap-login100">
    <div class="login100-pic js-tilt" data-tilt>
      <img style="margin-top: 70px;"
        src="https://images.squarespace-cdn.com/content/v1/52797d42e4b01f648b9e8392/1455601046694-12NE4QQDGEHQ6TDTRHYJ/Blueconic__Chair_WhiteBG-trzown.gif?format=500w"
        alt="IMG">
    </div>

    <form method="POST" enctype="multipart/form-data" class="login100-form validate-form">
      {% csrf_token %}
      <span class="login100-form-title">
        <span class="badge badge-dark  text-center">ADMIN ONLY <i class="fa fa-user-circle"></i></span>
      </span>
      <p class="text-center"><b>Note: </b> Only the <strong>Admin</strong> can login from here. <br> No
        <strong>Client</strong> will be allowed to login.</p><br>
      <div class="wrap-input100 validate-input" data-validate="Valid email is required: ex@abc.xyz">
        <input style="outline: none;border: none;" class="input100" type="text" name="username"
          placeholder="Enter your username">
        <span class="focus-input100"></span>
        <span class="symbol-input100">
          <i class="fa fa-user-circle-o" aria-hidden="true"></i>
        </span>
      </div>

      <div class="wrap-input100 validate-input" data-validate="Password is required">
        <input style="outline: none;border: none;" class="input100" type="password" name="password"
          placeholder="Enter Password">
        <span class="focus-input100"></span>
        <span class="symbol-input100">
          <i class="fa fa-lock" aria-hidden="true"></i>
        </span>
      </div>


      <div class="container-login100-form-btn">
        <button class="login100-form-btn">
          Login
        </button>
      </div>


    </form>
  </div>
</div>



{% endblock %}

templates/base.html
{% load static%}
{% load bootstrap4 %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">

  {% if title %}
  <title>Store-Centre - {{title}}</title>
  {% else %}
  <title> Store-Centre </title>
  {% endif %}

  {% block styles %}

  <link rel="icon" href="/static/images/pool2.png" type="image" sizes="16x16">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300&family=Shalimar&display=swap"
    rel="stylesheet">

  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,900|Oswald:300,400,700" rel="stylesheet">
  <link rel="stylesheet" href="/static/fonts/icomoon/style.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
  <link rel="stylesheet" href="/static/css/jquery-ui.css">
  <link rel="stylesheet" href="/static/css/owl.carousel.min.css">
  <link rel="stylesheet" href="/static/css/owl.theme.default.min.css">
  <link rel="stylesheet" href="/static/css/owl.theme.default.min.css">
  <link rel="stylesheet" href="/static/css/jquery.fancybox.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
  <link rel="stylesheet" href="/static/css/bootstrap-datepicker.css">
  <link href="https://fonts.googleapis.com/css?family=Kaushan+Script|Source+Sans+Pro" rel="stylesheet">
  <link rel="stylesheet" href="/static/fonts/flaticon/font/flaticon.css">

  <link rel="stylesheet" href="/static/css/aos.css">
  <link rel="stylesheet" href="/static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="/static/css/hamburgers.min.css">
  <link rel="stylesheet" href="/static/css/select2.min.css">
  <link rel="stylesheet" href="/static/css/util.css">
  <link rel="stylesheet" href="/static/css/themify-icons.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    integrity="sha512-c42qTSw/wPZ3/5LBzD+Bw5f7bSF2oxou6wEb+I/lqeaKV5FDIfMvvRp772y4jcJLKuGUOpbJMdg/BTl50fJYAw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="/static/css/date-picker/css/datepicker.min.css">
  <link rel="stylesheet" href="/static/css/loginform.css">
  <link rel="stylesheet" href="/static/css/form.css">
  <link rel="stylesheet" href="/static/css/help.css">
  <link rel="stylesheet" href="/static/css/style.css">
  <link rel="stylesheet" href="/static/css/pay.css">
  <link rel="stylesheet" href="/static/css/ionicons.min.css">
  <link rel="stylesheet" href="/static/css/flaticon.css">
  <link rel="stylesheet" href="/static/css/fess.css">
  <link rel="stylesheet" href="/static/css/blog.css">
  <link rel="stylesheet" href="/static/css/loader.css">

  {% endblock %}

</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
  <!-- Preloader Start -->
  <div id="preloader-active">
    <div class="preloader d-flex align-items-center justify-content-center">
      <div class=" position-relative">
        <div class="preloader-circle"></div>
        <div class="preloader-img pere-text">
          <img src="/static/images/pool2.png" width="50" alt="">
        </div>
        <h3 class="text-center animate__animated animate__zoomIn"><span class="text-info ">STORE </span><span
            class="text-dark"> 2</span><span style="color: red;">5</span><span style="color: green;">4</span></h3>
      </div>
    </div>
  </div>
  <!-- Preloader Start -->


  <div class="site-wrap">
    {% include "navbar.html" %}

    {% if messages %}
    {% for message in messages %}
    <div class="row pt-5">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <div class="alert text-center {{ message.tags }} alert-dismissible" role="alert" id="messages">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message }}
        </div>
      </div>
      <div class="col-md-4"></div>
    </div>
    {% endfor %}
    {% endif %}

    {% block content %}


    {%endblock%}



    {% block scripts %}


    <script src="/static/js/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="/static/js/loader.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script src="/static/js/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.20.3/TweenMax.min.js"></script>
    <script src="/static/js/owl.carousel.min.js"></script>
    <script src="/static/css/date-picker/js/datepicker.js"></script>
    <script src="/static/css/date-picker/js/datepicker.en.js"></script>
    <script src="/static/js/jquery.countdown.min.js"></script>
    <script src="/static/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src="/static/js/aos.js"></script>
    <script src="/static/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.js"></script>
    <script src="/static/js/tilt.jquery.min.js"></script>
    <script src="/static/js/jquery.fancybox.min.js"></script>
    <script src="/static/js/jquery.sticky.js"></script>
    <script src="/static/js/help.js"></script>
    <script src="/static/js/main.js"></script>
    <script src="/static/js/grunt.js"></script>
    <script src="/static/js/pass.js"></script>
    <script src="/static/js/loginform.js"></script>
    <script>
      $('.js-tilt').tilt({
        scale: 1.1
      })
      $(document).ready(function () {
        Date.prototype.toDateInputValue = (function () {
          var local = new Date(this);
          local.setMinutes(this.getMinutes() - this.getTimezoneOffset());
          return local.toJSON().slice(0, 10);
        });

        // calculate diff in days
        function findDayDifference(departure, arrival) {
          var date1 = new Date(departure);
          var date2 = new Date(arrival);
          // always round down
          return Math.floor((Math.abs(date2 - date1)) / (1000 * 60 * 60 * 24));
        }
        total = function () {

          var departure = $('#departure_date').val();
          var arrival = $('#arrival_date').val();

          var units = $('#no_of_units').val();


          no_of_days = findDayDifference(departure, arrival)
          total_cost = no_of_days * charge * units;
          $('#total_cost').attr('value', total_cost);

        }

        //set date values to today on load
        $('#departure_date').val(new Date().toDateInputValue());
        $('#arrival_date').val(new Date().toDateInputValue());

        var charge = $("#id_storage_type").find('option:selected').attr('charge')
        var units = 0;
        total()

        $("#id_storage_type").change(function () {
          var element = $(this).find('option:selected');
          value = element.attr("value")
          console.log(typeof value)
          charge = parseInt(element.attr("charge"));
          total();
        });
        $("#no_of_units").on('input', function () {
          units = $(this).val();
          console.log(units)
          total();
        });


        $(document).ready(function () {
          if (document.cookie.indexOf("FooBar=true") == -1) {
            document.cookie = "FooBar=true; max-age=86400"; // 86400: seconds in a day
            $('#MyModal').modal('show');
          }
        });



      });
    </script>


    {% endblock %}
    {% include "footer.html" %}
  </div>
</body>

</html>

templates/change_password.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Change Password {% endblock %}
{% block css %}
{% endblock %}

{% block content %}

<div class="overlay"
    style="box-shadow:inset 0 0 0 2000px rgba(23, 34, 23, 0.863);background-image: url(/static/images/hero_1.jpg);color: white;"
    data-aos="fade" id="home-section">


    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-md-6 mt-lg-5 text-center">
                <br><br>
                <h1>Reset Password</h1>
                <div style="margin-bottom: 10px;">
                </div>
            </div>
        </div>
    </div>
    <br><br>
    <a href="#heading" class="smoothscroll arrow-down"><span class="icon-arrow_downward"></span></a>
</div>




<form class="container mt-3" method="POST" name="change_password" onsubmit="return checkPassword()">
    {% csrf_token %}
    <div class="row mt-4">
        <div class="form-group col-md-6">
            <label><i style="font-weight: bold;">Username</i></label>
            <input type="text" class="form-control mt-2" name="username" value="{{request.user}}" readonly>
        </div>
        <div class="form-group col-md-6">
            <label><i style="font-weight: bold;">Current Password</i></label>
            <input type="password" class="form-control mt-2" name="current_password" placeholder="Current Password">
        </div>
    </div>

    <div class="row mt-4">
        <div class="form-group col-md-12">
            <label><i style="font-weight: bold;">New Password</i></label>
            <input type="password" class="form-control mt-2" name="new_password" placeholder="Enter the new password">
        </div>
    </div>

    <div class="row mt-4">
        <div class="form-group col-md-12">
            <label><i style="font-weight: bold;">Confirm Password</i></label>
            <input type="password" class="form-control mt-2" name="confirm_password" placeholder="Confirm the new password">
        </div>
    </div>

    <input type="submit" class="btn btn-outline-primary mt-4" value="Update Password">
</form>
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}


{% load static %}

{% block content %}

<div class="overlay"
    style="box-shadow:inset 0 0 0 2000px rgba(23, 34, 23, 0.863);background-image: url(/static/images/hero_1.jpg);color: white;"
    data-aos="fade" id="home-section">


    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-md-6 mt-lg-5 text-center">
                <br><br>
                <h1>Checkout</h1>
                <div style="margin-bottom: 10px;">
                </div>
            </div>
        </div>
    </div>
    <br><br>
    <a href="#bs" class="smoothscroll arrow-down"><span class="icon-arrow_downward"></span></a>
</div>



<div class="container" style="min-height:45vh;margin-top: 100px;">
    <div class="summary mt-5 row" >
        <div class="col-sm-2"></div>
        <div class="col-sm-8">
            <div class="card">
                <div class="card-body">
                <h2 class="card-title">Checkout</h2>
                <p class="card-text">{{goods.description}}</p>
                <a class="card-link btn btn-outline-danger" href="{% url 'records'%}">Cancel</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a class="btn btn-primary card-link"
                    href="{% url 'checkout_goods' goods.id %}"> Checkout</a>
            </div>
        </div>
        </div>
        <div class="col-sm-2"></div>

    </div>
</div>
{% endblock %}

templates/footer.html
{% load bootstrap4 %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
<footer class="site-footer" style="margin-bottom: 300px;">
    <div class="container" >
      <div class="row">
        <div class="col-md-8">
          <div class="row">
            <div class="col-md-5">
              <h2 class="footer-heading mb-4">About Us</h2>
              <p>We provide a range of storage facilities based on the type of goods that clients need to be stored</p>
            </div>
            <div class="col-md-3 mx-auto">
              <h2 class="footer-heading mb-4">Quick Links</h2>
              <ul class="list-unstyled">
                <li><a href="#">About Us</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Testimonials</a></li>
                <li><a href="#">Contact Us</a></li>
              </ul>
            </div>
            
          </div>
        </div>
        <div class="col-md-4">
          <div class="mb-4">
            <h2 class="footer-heading mb-4">Subscribe Newsletter</h2>
          <form action="{% url 'subscribe' %}" method="post" class="footer-subscribe">
            {% csrf_token %}
            <div class="input-group mb-3">
              <input type="email" name="email" class="form-control border-secondary text-white bg-transparent" required placeholder="Enter Email" aria-label="Enter Email" aria-describedby="button-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary text-black" type="submit" id="button-addon2">Send</button>
              </div>
            </div>
          </form> 

          <!-- <div class="container-fluid text-center">
            <h1>Subscribe To Our Emailing Service</h1>
              {% if messages %}
                  {% for message in messages %}
                      <p style="color:green">{{ message }}</p>
                  {% endfor %}
              {% endif %}
              <form action="{% url 'subscribe' %}" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    
                  </div>
                  {% render_field form.email|append_attr:"required" placeholder="Your Email" %}
                  <input type="submit" value="Submit">
              </form>
          </div> -->


          </div>
          
          <div class="">
            <h2 class="footer-heading mb-4">Follow Us</h2>
              <a href="#" class="pl-0 pr-3"><span class="icon-facebook"></span></a>
              <a href="#" class="pl-3 pr-3"><span class="icon-twitter"></span></a>
              <a href="#" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
              <a href="#" class="pl-3 pr-3"><span class="icon-linkedin"></span></a>
          </div>


        </div>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-md-12">
        <div class="border-top" style="margin-top:120px;">
        <p class="copyright pt-4"><small>&copy; <script>document.write(new Date().getFullYear());</script> StoreCentre. All Rights Reserved By.<a href="/" target="_blank">Store.com</a></small></p>
        </div>
      </div>
      
    </div>
  </footer>

  <a href="#top" style="border-radius: 80px;background-color: darkcyan;" class="gototop"><span class="icon-angle-double-up"></span></a>

 {%endblock%}

templates/transport_approval_email.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Transport Request Summary</title>

  <link rel="icon" href="/favicon.ico">
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">

</head>

<body>
    <p>Dear {{request_summary.user.first_name|title}}, <br>
        Your {{request_summary.transport_type|title}} transport request ID#{{request_summary.id}} has been approved. Your request is on its way!</p><br>
    <br><p>Kind regards,<br>StoreCentre254 Management</p>
</body>
</html>